// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/auth/signup/email/exist": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "授权"
                ],
                "summary": "校验邮箱是否已注册",
                "parameters": [
                    {
                        "type": "string",
                        "description": "邮箱",
                        "name": "email",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":true,\"msg\":\"success\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/auth/signup/phone/exist": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "授权"
                ],
                "summary": "校验手机号是否已注册",
                "parameters": [
                    {
                        "type": "string",
                        "description": "手机号码",
                        "name": "phone",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"exist\":true,\"msg\":\"ok\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/auth/signup/using-phone": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "授权"
                ],
                "summary": "使用手机验证码进行注册",
                "parameters": [
                    {
                        "type": "string",
                        "description": "手机号",
                        "name": "phone",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "用户名",
                        "name": "name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "密码",
                        "name": "password",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "确认密码",
                        "name": "password_confirm",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "短信验证码",
                        "name": "verify_code",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":true,\"msg\":\"success\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/verify-codes/captcha": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "授权"
                ],
                "summary": "获取图片验证码",
                "responses": {
                    "200": {
                        "description": "{\"captcha_id\":1,\"data\":\"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/verify-codes/phone": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "授权"
                ],
                "summary": "发送短信验证码(前提先获取图片验证码)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "手机号码",
                        "name": "phone",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "图片验证码ID",
                        "name": "captcha_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "图片验证码答案",
                        "name": "captcha_answer",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":\"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
