info:
  contact: {}
paths:
  /v1/auth/login/refresh-token:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":true,"msg":"success"}'
          schema:
            type: string
      summary: 刷新令牌(延长时间)
      tags:
      - 授权
  /v1/auth/login/using-password:
    post:
      parameters:
      - description: 填手机号/email/用户名
        in: query
        name: login_id
        required: true
        type: string
      - description: 密码
        in: query
        name: password
        required: true
        type: string
      - description: 图形验证码id
        in: query
        name: captcha_id
        required: true
        type: string
      - description: 图形验证码
        in: query
        name: captcha_answer
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":true,"msg":"success"}'
          schema:
            type: string
      summary: 使用密码登录
      tags:
      - 授权
  /v1/auth/login/using-phone:
    post:
      parameters:
      - description: 手机号
        in: query
        name: phone
        required: true
        type: string
      - description: 短信验证码
        in: query
        name: verify_code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":true,"msg":"success"}'
          schema:
            type: string
      summary: 使用手机验证码进行登录
      tags:
      - 授权
  /v1/auth/password-reset/using-phone:
    post:
      parameters:
      - description: 手机号
        in: query
        name: phone
        required: true
        type: string
      - description: 短信验证码
        in: query
        name: verify_code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":true,"msg":"success"}'
          schema:
            type: string
      summary: 找回密码(通过手机号+短信验证码)
      tags:
      - 授权
  /v1/auth/signup/email/exist:
    post:
      parameters:
      - description: 邮箱
        in: query
        name: email
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":true,"msg":"success"}'
          schema:
            type: string
      summary: 校验邮箱是否已注册
      tags:
      - 授权
  /v1/auth/signup/phone/exist:
    post:
      parameters:
      - description: 手机号码
        in: query
        name: phone
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"exist":true,"msg":"ok"}'
          schema:
            type: string
      summary: 校验手机号是否已注册
      tags:
      - 授权
  /v1/auth/signup/using-phone:
    post:
      parameters:
      - description: 手机号
        in: query
        name: phone
        required: true
        type: string
      - description: 用户名
        in: query
        name: name
        required: true
        type: string
      - description: 密码
        in: query
        name: password
        required: true
        type: string
      - description: 确认密码
        in: query
        name: password_confirm
        required: true
        type: string
      - description: 短信验证码
        in: query
        name: verify_code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":true,"msg":"success"}'
          schema:
            type: string
      summary: 使用手机验证码进行注册
      tags:
      - 授权
  /v1/categories:
    get:
      parameters:
      - description: 分类名
        in: query
        name: name
        required: true
        type: string
      - description: 描述
        in: query
        name: description
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":true,"msg":"success"}'
          schema:
            type: string
      summary: 分类列表
      tags:
      - 内容
    post:
      parameters:
      - description: 分类名
        in: query
        name: name
        required: true
        type: string
      - description: 描述
        in: query
        name: description
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":true,"msg":"success"}'
          schema:
            type: string
      summary: 创建分类
      tags:
      - 内容
  /v1/categories/:id:
    delete:
      parameters:
      - description: 分类名
        in: query
        name: name
        required: true
        type: string
      - description: 描述
        in: query
        name: description
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":true,"msg":"success"}'
          schema:
            type: string
      summary: 删除分类
      tags:
      - 内容
    put:
      parameters:
      - description: 分类名
        in: query
        name: name
        required: true
        type: string
      - description: 描述
        in: query
        name: description
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":true,"msg":"success"}'
          schema:
            type: string
      summary: 修改分类
      tags:
      - 内容
  /v1/user:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":true,"msg":"success"}'
          schema:
            type: string
      summary: 获取当前用户
      tags:
      - 用户
  /v1/users:
    get:
      parameters:
      - description: 排序(id/created_at/updated_at,默认id)
        in: query
        name: sort
        type: string
      - description: 排序规则(仅支持 asc（正序）,desc（倒序）)
        in: query
        name: order
        type: string
      - description: 每页条数(介于 2~100 之间)
        in: query
        name: per_page
        type: string
      - description: 当前页
        in: query
        name: page
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":true,"msg":"success"}'
          schema:
            type: string
      summary: 获取所有用户
      tags:
      - 用户
  /verify-codes/captcha:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: '{"captcha_id":1,"data":""}'
          schema:
            type: string
      summary: 获取图片验证码
      tags:
      - 授权
  /verify-codes/phone:
    post:
      parameters:
      - description: 手机号码
        in: query
        name: phone
        required: true
        type: string
      - description: 图片验证码ID
        in: query
        name: captcha_id
        required: true
        type: string
      - description: 图片验证码答案
        in: query
        name: captcha_answer
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":""}'
          schema:
            type: string
      summary: 发送短信验证码(前提先获取图片验证码)
      tags:
      - 授权
swagger: "2.0"
