info:
  contact: {}
paths:
  /v1/auth/signup/phone/exist:
    post:
      parameters:
      - description: 手机号码
        in: query
        name: phone
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"exist":true,"msg":"ok"}'
          schema:
            type: string
      summary: 校验手机号是否已注册
      tags:
      - 授权
swagger: "2.0"
