info:
  contact: {}
paths:
  /v1/auth/signup/email/exist:
    post:
      parameters:
      - description: 邮箱
        in: query
        name: email
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":true,"msg":"success"}'
          schema:
            type: string
      summary: 校验邮箱是否已注册
      tags:
      - 授权
  /v1/auth/signup/phone/exist:
    post:
      parameters:
      - description: 手机号码
        in: query
        name: phone
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"exist":true,"msg":"ok"}'
          schema:
            type: string
      summary: 校验手机号是否已注册
      tags:
      - 授权
  /verify-codes/captcha:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: '{"captcha_id":1,"data":""}'
          schema:
            type: string
      summary: 获取图片验证码
      tags:
      - 授权
  /verify-codes/phone:
    post:
      parameters:
      - description: 手机号码
        in: query
        name: phone
        required: true
        type: string
      - description: 图片验证码ID
        in: query
        name: captcha_id
        required: true
        type: string
      - description: 图片验证码答案
        in: query
        name: captcha_answer
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":""}'
          schema:
            type: string
      summary: 发送短信验证码
      tags:
      - 授权
swagger: "2.0"
